-- Canonical Caribbean genre taxonomy. Additive and admin-editable after seeding.
insert into genres (slug,name,description) values
('calypso','Calypso','Trinidad and Tobago narrative and topical song tradition.'),
('kaiso','Kaiso','Distinct Trinidad and Tobago kaiso tradition; not collapsed into Calypso.'),
('extempo','Extempo','Improvisational Trinidad and Tobago calypso tradition.'),
('santimanitay','Santimanitay','Santimanitay challenge/refrain tradition connected to extempo and Kalinda contexts.'),
('lavway','Lavway / Lavwé','Call-and-response chant tradition associated with Trinidad and Tobago Kalinda stickfighting.'),
('ai-steelpan','AI Steelpan','AI-generated or AI-assisted music centered on steelpan.'),
('steelpan','Steelpan','Music centered on steelpan.'),
('reggae','Reggae','Reggae.'),
('roots-reggae','Roots Reggae','Roots reggae.'),
('modern-reggae','Modern Reggae','Contemporary reggae.'),
('country-reggae','Country Reggae','Country and reggae fusion.'),
('dancehall','Dancehall','Dancehall.'),
('dub','Dub','Dub.'),
('lovers-rock','Lovers Rock','Lovers rock.'),
('rocksteady','Rocksteady','Rocksteady.'),
('ska','Ska','Ska.'),
('mento','Mento','Mento.'),
('soca','Soca','Soca.'),
('power-soca','Power Soca','Power soca.'),
('groovy-soca','Groovy Soca','Groovy soca.'),
('chutney','Chutney','Indo-Caribbean chutney music.'),
('chutney-soca','Chutney Soca','Chutney and soca fusion.'),
('dennery-segment','Dennery Segment','Saint Lucian Dennery Segment.'),
('bouyon','Bouyon','Dominican bouyon.'),
('kompa','Kompa','Haitian kompa.'),
('zouk','Zouk','French Caribbean zouk.'),
('caribbean-gospel','Caribbean Gospel','Caribbean gospel.'),
('caribbean-rnb','Caribbean R&B','Caribbean R&B.'),
('caribbean-hip-hop','Caribbean Hip Hop','Caribbean hip hop.'),
('caribbean-rap','Caribbean Rap','Caribbean rap.'),
('afro-caribbean','Afro-Caribbean','Afro-Caribbean fusion.'),
('island-pop','Island Pop','Caribbean island pop.'),
('caribbean-fusion','Caribbean Fusion','Caribbean fusion.'),
('instrumental','Instrumental','Instrumental music.'),
('riddim','Riddim','Riddim / production intended for voicing.'),
('beat','Beat','Beat / production.'),
('backing-track','Backing Track','Backing track.'),
('production-version','Production / Version','Production, version or alternate instrumental form.')
on conflict (slug) do update set name=excluded.name, description=excluded.description;
