import { databaseConfigured, query } from '../../lib/db';

export const metadata = { title:'The Riddim Yard — Caribbean Riddims, Beats & Instrumentals', description:'Discover published Caribbean riddims, beats, instrumentals and productions, then trace the songs voiced on each production.' };

export default async function RiddimYard(){
  let productions=[];
  if(databaseConfigured())try{const result=await query(`select p.slug,p.title,p.production_type,p.bpm,p.musical_key,p.rights_state,a.display_name producer,count(r.id)::int song_count from productions p left join artists a on a.id=p.producer_artist_id left join recordings r on r.production_id=p.id and r.publication_state='PUBLISHED' where p.publication_state='published' group by p.id,a.display_name order by p.created_at desc limit 100`);productions=result.rows;}catch(error){console.error('riddim_yard_read_failed',error?.message||error);}
  return <main className="detailShell"><section className="detailHero compact"><span className="eyebrow">THE RIDDIM YARD</span><h1>The production behind the record.</h1><p>Riddims, beats, instrumentals and backing tracks are first-class Caribbean catalogue objects. Each production can connect to every verified published song voiced on it.</p></section><section className="detailSection"><div className="resultGrid">{productions.map(item=><a className="resultCard" href={`/riddims/${item.slug}`} key={item.slug}><span className="resultType">{String(item.production_type).replaceAll('_',' ')}</span><strong>{item.title}</strong><small>{[item.producer,item.bpm?`${item.bpm} BPM`:null,item.musical_key,item.song_count?`${item.song_count} songs`:null].filter(Boolean).join(' · ')}</small><span>→</span></a>)}{!productions.length?<a className="resultCard" href="/riddims/midnight-cane-riddim"><span className="resultType">DEMO METADATA ONLY</span><strong>Midnight Cane Riddim</strong><small>No audio, licence or fake producer identity is asserted.</small><span>→</span></a>:null}</div></section></main>;
}
